/*
 * BrainRex API
 * The Brainrex API is a collection of analytics tools and data integrations made for blockchain developers. In particular we offer Natural Language Processing and Anomaly detection algorithms that have been fine tune to understand text data and time series in the domain speficic setting of cryptocurrency and blockchain technology. This technology is intended to be use as building blocks to bigger applications, we offer examples on how to use them for Trading Backtesting and Smart Contract anomaly monitoring.
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * ExchangeAssetsResponseInner
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-06-14T16:16:45.442340731Z[GMT]")

public class ExchangeAssetsResponseInner {
  @SerializedName("name")
  private String name = null;

  @SerializedName("id")
  private BigDecimal id = null;

  @SerializedName("tradinSym")
  private String tradinSym = null;

  @SerializedName("symbol")
  private String symbol = null;

  public ExchangeAssetsResponseInner name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Highest price of the time frame with two decimal points
   * @return name
  **/
  @Schema(example = "Ethereum", description = "Highest price of the time frame with two decimal points")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ExchangeAssetsResponseInner id(BigDecimal id) {
    this.id = id;
    return this;
  }

   /**
   * Percetange change in the last 24 hours
   * @return id
  **/
  @Schema(example = "33", description = "Percetange change in the last 24 hours")
  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }

  public ExchangeAssetsResponseInner tradinSym(String tradinSym) {
    this.tradinSym = tradinSym;
    return this;
  }

   /**
   * Volume of currency exchanged in the time frame with two decimal points
   * @return tradinSym
  **/
  @Schema(example = "ETH", description = "Volume of currency exchanged in the time frame with two decimal points")
  public String getTradinSym() {
    return tradinSym;
  }

  public void setTradinSym(String tradinSym) {
    this.tradinSym = tradinSym;
  }

  public ExchangeAssetsResponseInner symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Volume of currency exchanged in the time frame with two decimal points
   * @return symbol
  **/
  @Schema(example = "ETH", description = "Volume of currency exchanged in the time frame with two decimal points")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExchangeAssetsResponseInner exchangeAssetsResponseInner = (ExchangeAssetsResponseInner) o;
    return Objects.equals(this.name, exchangeAssetsResponseInner.name) &&
        Objects.equals(this.id, exchangeAssetsResponseInner.id) &&
        Objects.equals(this.tradinSym, exchangeAssetsResponseInner.tradinSym) &&
        Objects.equals(this.symbol, exchangeAssetsResponseInner.symbol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, id, tradinSym, symbol);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExchangeAssetsResponseInner {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tradinSym: ").append(toIndentedString(tradinSym)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
