/*
 * Brainrex API Explorer
 * This is the Brainrex API. You can find Market Data and Sentiment Analysis endpoints.More about Brainrex at [http://brainrex.com](http://brainrex.com) or on [slack.brainrex.com, #brainrex](http://slack.brainrex.com).      For this sample, you only need to login to the Brainrex for Developers site. IMPORTANT NOTICE: FACE-ID API still in development, generate and download methods haven't been implemented at backend
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@brainrex.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Request2
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-09-26T20:35:05.506Z")
public class Request2 {
  @SerializedName("exchange")
  private String exchange = null;

  @SerializedName("market")
  private String market = null;

  @SerializedName("data_format")
  private String dataFormat = null;

  @SerializedName("orient")
  private String orient = null;

  @SerializedName("candle_size")
  private String candleSize = null;

  @SerializedName("start_date")
  private String startDate = null;

  @SerializedName("end_date")
  private String endDate = null;

  public Request2 exchange(String exchange) {
    this.exchange = exchange;
    return this;
  }

   /**
   * Name of the exchange
   * @return exchange
  **/
  @ApiModelProperty(example = "bitstamp", value = "Name of the exchange")
  public String getExchange() {
    return exchange;
  }

  public void setExchange(String exchange) {
    this.exchange = exchange;
  }

  public Request2 market(String market) {
    this.market = market;
    return this;
  }

   /**
   * Name of the currency pair
   * @return market
  **/
  @ApiModelProperty(example = "BTC-USD", value = "Name of the currency pair")
  public String getMarket() {
    return market;
  }

  public void setMarket(String market) {
    this.market = market;
  }

  public Request2 dataFormat(String dataFormat) {
    this.dataFormat = dataFormat;
    return this;
  }

   /**
   * Name of the data format availables (standard)
   * @return dataFormat
  **/
  @ApiModelProperty(example = "standard", value = "Name of the data format availables (standard)")
  public String getDataFormat() {
    return dataFormat;
  }

  public void setDataFormat(String dataFormat) {
    this.dataFormat = dataFormat;
  }

  public Request2 orient(String orient) {
    this.orient = orient;
    return this;
  }

   /**
   * Name of the market
   * @return orient
  **/
  @ApiModelProperty(example = "records", value = "Name of the market")
  public String getOrient() {
    return orient;
  }

  public void setOrient(String orient) {
    this.orient = orient;
  }

  public Request2 candleSize(String candleSize) {
    this.candleSize = candleSize;
    return this;
  }

   /**
   * Name of the market
   * @return candleSize
  **/
  @ApiModelProperty(example = "6h", value = "Name of the market")
  public String getCandleSize() {
    return candleSize;
  }

  public void setCandleSize(String candleSize) {
    this.candleSize = candleSize;
  }

  public Request2 startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Name of the market 2014-01-01
   * @return startDate
  **/
  @ApiModelProperty(value = "Name of the market 2014-01-01")
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }

  public Request2 endDate(String endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Name of the market 2014-01-01
   * @return endDate
  **/
  @ApiModelProperty(value = "Name of the market 2014-01-01")
  public String getEndDate() {
    return endDate;
  }

  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Request2 request2 = (Request2) o;
    return Objects.equals(this.exchange, request2.exchange) &&
        Objects.equals(this.market, request2.market) &&
        Objects.equals(this.dataFormat, request2.dataFormat) &&
        Objects.equals(this.orient, request2.orient) &&
        Objects.equals(this.candleSize, request2.candleSize) &&
        Objects.equals(this.startDate, request2.startDate) &&
        Objects.equals(this.endDate, request2.endDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exchange, market, dataFormat, orient, candleSize, startDate, endDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Request2 {\n");
    
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    market: ").append(toIndentedString(market)).append("\n");
    sb.append("    dataFormat: ").append(toIndentedString(dataFormat)).append("\n");
    sb.append("    orient: ").append(toIndentedString(orient)).append("\n");
    sb.append("    candleSize: ").append(toIndentedString(candleSize)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

