/*
 * Brainrex API Explorer
 * This is the Brainrex API. You can find Market Data and Sentiment Analysis endpoints.More about Brainrex at [http://brainrex.com](http://brainrex.com) or on [slack.brainrex.com, #brainrex](http://slack.brainrex.com).      For this sample, you only need to login to the Brainrex for Developers site. IMPORTANT NOTICE: FACE-ID API still in development, generate and download methods haven't been implemented at backend
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@brainrex.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Request;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BlockchainApiApi
 */
@Ignore
public class BlockchainApiApiTest {

    private final BlockchainApiApi api = new BlockchainApiApi();

    
    /**
     * Download raw ticker data from major crypto markets
     *
     * Downloads specified asset class and market and time frame. Of our raw ticker data format
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void blockchainAverageTxTest() throws ApiException {
        Request request = null;
        String response = api.blockchainAverageTx(request);

        // TODO: test validations
    }
    
    /**
     * The blockchains data structure supported by the Brainrex API
     *
     * List of supported blockchains networks for analysis. The full history of the networks are available.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void blockchainListTest() throws ApiException {
        List<Object> response = api.blockchainList();

        // TODO: test validations
    }
    
}
