/*
 * Brainrex API Explorer
 * This is the Brainrex API. You can find Market Data and Sentiment Analysis endpoints.More about Brainrex at [http://brainrex.com](http://brainrex.com) or on [slack.brainrex.com, #brainrex](http://slack.brainrex.com).      For this sample, you only need to login to the Brainrex for Developers site. IMPORTANT NOTICE: FACE-ID API still in development, generate and download methods haven't been implemented at backend
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@brainrex.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Request1;
import io.swagger.client.model.Request2;
import io.swagger.client.model.Request3;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CryptoApiApi
 */
@Ignore
public class CryptoApiApiTest {

    private final CryptoApiApi api = new CryptoApiApi();

    
    /**
     * Downloads candle format market data
     *
     * Returns a list of candle data from specified market and data range
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void exchangesDownloadCandlesTest() throws ApiException {
        Request2 request = null;
        api.exchangesDownloadCandles(request);

        // TODO: test validations
    }
    
    /**
     * The markets data structure supported by the Brainrex Market API
     *
     * Read the list of supported markets ( currency pairs ) in each exchange
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void exchangesListTest() throws ApiException {
        List<Object> response = api.exchangesList();

        // TODO: test validations
    }
    
    /**
     * Download raw ticker data from major crypto markets
     *
     * Downloads specified asset class and market and time frame. Of our raw ticker data format
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void exchangesMarketmakerTest() throws ApiException {
        Request3 request = null;
        String response = api.exchangesMarketmaker(request);

        // TODO: test validations
    }
    
    /**
     * The exchanges data structure supported by the Brainrex API
     *
     * Read the list of supported exchanges in the Market Data API
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void exchangesReadTest() throws ApiException {
        List<Object> response = api.exchangesRead();

        // TODO: test validations
    }
    
    /**
     * Download raw ticker data from major crypto markets
     *
     * Downloads specified asset class and market and time frame. Of our raw ticker data format
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void exchangesTickerDataDownloadTest() throws ApiException {
        Request1 request = null;
        String response = api.exchangesTickerDataDownload(request);

        // TODO: test validations
    }
    
}
