/*
 * Brainrex API Explorer
 * This is the Brainrex API. You can find Market Data and Sentiment Analysis endpoints.More about Brainrex at [http://brainrex.com](http://brainrex.com) or on [slack.brainrex.com, #brainrex](http://slack.brainrex.com).      For this sample, you only need to login to the Brainrex for Developers site. IMPORTANT NOTICE: FACE-ID API still in development, generate and download methods haven't been implemented at backend
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@brainrex.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Text1;
import io.swagger.client.model.Text2;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SentimentAnalysisApiApi
 */
@Ignore
public class SentimentAnalysisApiApiTest {

    private final SentimentAnalysisApiApi api = new SentimentAnalysisApiApi();

    
    /**
     * Sentiment analysis score using a model trained for buy signals.
     *
     * Gives a 0 to 1 score, depending on buy/sell sentiment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sentimentGetPriceSentimentTest() throws ApiException {
        Text2 text = null;
        String response = api.sentimentGetPriceSentiment(text);

        // TODO: test validations
    }
    
    /**
     * Sentiment analysis for any given blob of text
     *
     * Gives a -1 to 1 score, depending on bearish/bullish sentiment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sentimentGetSentimentTest() throws ApiException {
        Text1 text = null;
        String response = api.sentimentGetSentiment(text);

        // TODO: test validations
    }
    
}
